language: php
os: linux
dist: bionic

notifications:
  email: false

php:
  - 8.0.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer update -o --prefer-source --no-interaction
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - vendor/bin/phpunit --exclude-group internet --coverage-clover=build/clover.xml

after_success:
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
