language: php
os: linux
dist: bionic

notifications:
  email: false

php:
  - 8.0.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer update -o --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --exclude-group internet --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
