language: php
os: linux
dist: xenial

notifications:
  email: false

php:
  - '7.3'
  - '7.4'
  - 'nightly'

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  fast_finish: true
  allow_failures:
    - php: '7.3'
    - php: '7.4'
    - php: 'nightly'

install:
  - composer update -o --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --exclude-group internet --coverage-clover build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
