language: php

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true

install:
  - composer update -o --no-interaction --prefer-stable --ignore-platform-reqs

script:
  - vendor/bin/phpunit --coverage-clover build/coverage/clover.xml

after_success:
  - travis_retry vendor/bin/codacycoverage clover build/coverage/clover.xml

sudo: false

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
