name: CI

on:
  pull_request:
  push:
    branches:
      - master

env:
  timezone: UTC
  REQUIRED_PHP_EXTENSIONS: 'curl fileinfo libxml mbstring zip'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.1'
          - '8.2'
          - '8.3'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          ini_values: opcache.enable=0
          coverage: pcov

      - name: Install composer and update
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--prefer-dist --no-progress --no-interaction'
          dependency-versions: highest

      - name: Run unit test suite
        run: vendor/bin/phpunit --exclude integration --verbose --coverage-text

      - name: Run integration tests
        if: success() || failure()
        run: vendor/bin/phpunit --group integration --verbose
